version: 2.1
orbs:
  snyk: snyk/snyk@1.2.3
  
jobs:
  snyking:
    docker:
      - image: cimg/node:18.9.0
    steps:
      - checkout
      - snyk/scan:
          monitor-on-build: true
          token-variable: SNYK_TOKEN

workflows:
  test:
    jobs:
      - snyking
